
#Client only settings for Abnormals Core.
[client]

	#Slabfish patron hat settings.
	[client.slabfishSettings]
		#If the slabfish hat's custom type should be enabled. If false, the default swamp slabfish appears; Default: True
		typeEnabled = false
		#If the slabfish hat's backpack should be enabled; Default: True
		backpackEnabled = false
		#If the slabfish hat's sweater should be enabled; Default: True
		sweaterEnabled = false
		#If the slabfish hat should be enabled; Default: True
		enabled = false

