
[general]
	disable_mod = false
	space_modules = false
	shadow_text = true
	animations = false
	animationSpeed = 1.0
	background_color = 1867534416

[[modules_left]]
	name = "fps"
	color_high = 5635925
	color_med = 16777045
	color_low = 16733525
	enabled = true

	[modules_left.lines]
		fps = true

[[modules_left]]
	name = "location"
	name_color = 43520
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		dimension = true
		facing = false
		rotation = false
		light = false
		light_server = true
		highest_block = false
		highest_block_server = false
		biome = true
		local_difficulty = false
		days_played = true

[[modules_left]]
	name = "coords"
	name_color = 16733525
	color_x = 16733525
	color_y = 5635925
	color_z = 5636095
	enabled = true

	[modules_left.lines]
		player_coords = true
		block_coords = true
		chunk_relative_coords = true
		chunk_coords = true

[[modules_left]]
	name = "empty"
	enabled = true

	[modules_left.lines]
		nothing = true

[[modules_left]]
	name = "help"
	name_color = 16645526
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		pie_graph = true
		fps_tps = true
		help = true

[[modules_right]]
	name = "system"
	name_color = 16755200
	value_color = 5636095
	enabled = true

	[modules_right.lines]
		java_version = false
		memory_usage = true
		allocated_memory = true
		cpu = true
		display = false
		gpu = true
		opengl_version = true
		gpu_driver = true

[[modules_right]]
	name = "empty"
	enabled = true

	[modules_right.lines]
		nothing = true

[[modules_right]]
	name = "server"
	name_color = 11184810
	value_color = 16777045
	enabled = true

	[modules_right.lines]
		server_tick = true
		packets_sent = true
		packets_received = true

