
#Select A GUI Style
[gui_style]
	#Allowed Values: DEFAULT, VANILLA
	"Embroidery Thread" = "VANILLA"
	#Allowed Values: DEFAULT, VANILLA
	"Bed/Ladder Builder" = "VANILLA"
	#Allowed Values: DEFAULT, VANILLA
	"Blanket Loom" = "VANILLA"

